let pessoas = require("../pap1/pessoas")
const grupo = []
grupo.push(new pessoas ('F',1.65))
grupo.push(new pessoas ('F',1.73))
grupo.push(new pessoas ('F',1.67))
grupo.push(new pessoas ('F',1.75))
grupo.push(new pessoas ('F',1.62))
grupo.push(new pessoas ('F',1.60))
grupo.push(new pessoas ('F',1.69))
grupo.push(new pessoas ('M',1.97))
grupo.push(new pessoas ('M',1.90))
grupo.push(new pessoas ('M',1.78))
grupo.push(new pessoas ('M',1.79))
grupo.push(new pessoas ('M',1.85))
grupo.push(new pessoas ('M',1.80))
grupo.push(new pessoas ('M',1.88))
grupo.push(new pessoas ('M',1.95))
grupo.push(new pessoas ('F',1.74))
module.exports = grupo;